<?php

/**
 * Generated by bin/generate-contexts.php from resources/contexts/did-v1.jsonld,
 * the context published at https://www.w3.org/ns/did/v1.
 * Do not edit this file; run "composer generate-contexts" instead.
 *
 * This file includes material copied from or derived from
 * Decentralized Identifiers (DIDs) v1.0,
 * https://www.w3.org/TR/did-core/.
 * Copyright © 2022 W3C® (MIT, ERCIM, Keio, Beihang).
 * W3C Software and Document License, https://www.w3.org/copyright/software-license-2023/.
 * See the NOTICE file for the terms.
 */

declare(strict_types=1);

return [
    '@context' => [
        '@protected' => true,
        'id' => '@id',
        'type' => '@type',
        'alsoKnownAs' => [
            '@id' => 'https://www.w3.org/ns/activitystreams#alsoKnownAs',
            '@type' => '@id',
        ],
        'assertionMethod' => [
            '@id' => 'https://w3id.org/security#assertionMethod',
            '@type' => '@id',
            '@container' => '@set',
        ],
        'authentication' => [
            '@id' => 'https://w3id.org/security#authenticationMethod',
            '@type' => '@id',
            '@container' => '@set',
        ],
        'capabilityDelegation' => [
            '@id' => 'https://w3id.org/security#capabilityDelegationMethod',
            '@type' => '@id',
            '@container' => '@set',
        ],
        'capabilityInvocation' => [
            '@id' => 'https://w3id.org/security#capabilityInvocationMethod',
            '@type' => '@id',
            '@container' => '@set',
        ],
        'controller' => [
            '@id' => 'https://w3id.org/security#controller',
            '@type' => '@id',
        ],
        'keyAgreement' => [
            '@id' => 'https://w3id.org/security#keyAgreementMethod',
            '@type' => '@id',
            '@container' => '@set',
        ],
        'service' => [
            '@id' => 'https://www.w3.org/ns/did#service',
            '@type' => '@id',
            '@context' => [
                '@protected' => true,
                'id' => '@id',
                'type' => '@type',
                'serviceEndpoint' => [
                    '@id' => 'https://www.w3.org/ns/did#serviceEndpoint',
                    '@type' => '@id',
                ],
            ],
        ],
        'verificationMethod' => [
            '@id' => 'https://w3id.org/security#verificationMethod',
            '@type' => '@id',
        ],
    ],
];
