<?php

/**
 * Generated by bin/generate-contexts.php from resources/contexts/multikey-v1.jsonld,
 * the context published at https://w3id.org/security/multikey/v1.
 * Do not edit this file; run "composer generate-contexts" instead.
 *
 * This file includes material copied from or derived from
 * Verifiable Credential Data Integrity 1.0,
 * https://www.w3.org/TR/vc-data-integrity/.
 * Copyright © 2025 World Wide Web Consortium.
 * W3C Software and Document License, https://www.w3.org/copyright/software-license-2023/.
 * See the NOTICE file for the terms.
 */

declare(strict_types=1);

return [
    '@context' => [
        'id' => '@id',
        'type' => '@type',
        '@protected' => true,
        'Multikey' => [
            '@id' => 'https://w3id.org/security#Multikey',
            '@context' => [
                '@protected' => true,
                'id' => '@id',
                'type' => '@type',
                'controller' => [
                    '@id' => 'https://w3id.org/security#controller',
                    '@type' => '@id',
                ],
                'revoked' => [
                    '@id' => 'https://w3id.org/security#revoked',
                    '@type' => 'http://www.w3.org/2001/XMLSchema#dateTime',
                ],
                'expires' => [
                    '@id' => 'https://w3id.org/security#expiration',
                    '@type' => 'http://www.w3.org/2001/XMLSchema#dateTime',
                ],
                'publicKeyMultibase' => [
                    '@id' => 'https://w3id.org/security#publicKeyMultibase',
                    '@type' => 'https://w3id.org/security#multibase',
                ],
                'secretKeyMultibase' => [
                    '@id' => 'https://w3id.org/security#secretKeyMultibase',
                    '@type' => 'https://w3id.org/security#multibase',
                ],
            ],
        ],
    ],
];
